Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Gestion_Convention_stage.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Gestion_Convention_stage.Contexts;
using Gestion_Convention_stage.Utils;
using Newtonsoft.Json;


namespace Gestion_Convention_stage.Controllers
{
    public class AdminController : Controller
    {
        private readonly ILogger<AdminController> _logger;

        public AdminController(ILogger<AdminController> logger)
        {
            _logger = logger;
        }

       

        public IActionResult Demandes()
        {   
            return View( MyContext.fetchDemands());
        }

         public IActionResult History()
        {   
            ViewData["demandes"] = JsonConvert.SerializeObject(MyContext.fetchAllDemands());

            return View( );
        }

        public void validate(int id){
              
               MyContext.updateDemandeStatus(id,1);
               Mail.sendMail("" , "sadak_med@protonmail.com", "votre demande etait accepté" ,"Votre demande est pres au service de scolarite");
                Response.Redirect("Demandes",true);
               }
       
         public void refuse(int id){

                MyContext.updateDemandeStatus(id,-1);
               Mail.sendMail("" , "sadak_med@protonmail.com", "votre demande etait Refuse" ,"Votre demande est refuse change sil vvous plais merci.");
                Response.Redirect("Demandes",true);

        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Gestion_Convention_stage.Models;
using System.Text.Encodings.Web;
using Microsoft.AspNetCore.Mvc.Rendering;
using Gestion_Convention_stage.Contexts;

namespace Gestion_Convention_stage.Controllers
{
    public class StudentController:Controller
    {
     
        public static int apoge { get; set; }

        public IActionResult Signup()
        {
            return View();
        }

        public void Home(int apoge){
            StudentController.apoge=apoge;
            Response.Redirect("Demande",true);
        }

        public IActionResult Demande()
        {   Console.WriteLine("from Demande function "+ StudentController.apoge);
          Console.WriteLine("from Demande function viewData "+ ViewData["apoge"]);
            Demande dd= new Demande();
            dd.idStudent=StudentController.apoge;
            if (dd.checkDemande()==1 )
                ViewData["button"]="disabled";
            return View();
        }

        public IActionResult History()


        {   List<Demande> demandeList= new List<Demande>();
            Console.WriteLine(" from "+StudentController.apoge);
            demandeList=MyContext.fetchDemandeStudent(StudentController.apoge); 
            
            return View(demandeList);
        }

        public void saveStudent(Student student){

            StudentController.apoge=student.apoge;
            ViewData["apoge"]=student.apoge;
            student.demande=0;
            
            

            MyContext.InsertStudent(student);

            Response.Redirect("Demande",true);
        }
        public void saveDemande(Demande de){
            de.idStudent=StudentController.apoge;
            de.status=0;
            MyContext.InsertDemande(de);
            Response.Redirect("History",true);


        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gestion_Convention_stage</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3" >
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Gestion_Convention_stage</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
            </div>
        </nav>
    </header>
    <div class="container" style="margin-top:50px;">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Gestion_Convention_stage - <a asp-area="" asp-controller="Home" asp-action="Privacy">About</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout_admin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gestion_Convention_stage</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" >Gestion_Convention_stage</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Admin" asp-action="Demandes">Demandes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Admin" asp-action="History">History</a>
                        </li>
                    
                    </ul>
                </div>
                <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index" style="text-decoration:none; color:white;">Logout</a>

            </div>
        </nav>
    </header>
    <div class="container" style="margin-top:40px;">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Gestion_Convention_stage - <a asp-area="" asp-controller="Home" asp-action="Privacy">About</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        Splitting();
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout_student.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gestion_Convention_stage</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" >Gestion_Convention_stage</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Student" asp-action="Demande">Demande</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Student" asp-action="History">History</a>
                        </li>
                           <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Logout</a>
                        </li>
                    </ul>

                  

                </div>
            </div>
        </nav>
    </header>
    <div class="container" style="margin-top:40px;">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Gestion_Convention_stage - <a asp-area="" asp-controller="Home" asp-action="Privacy">About</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>